# Generated by Django 6.0.3 on 2026-04-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tecnologia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "verbose_name_plural": "Tecnologías",
            },
        ),
        migrations.CreateModel(
            name="Funcionario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_completo", models.CharField(max_length=200)),
                ("rut", models.CharField(max_length=12, unique=True)),
                (
                    "grado",
                    models.CharField(
                        help_text="Ej: Sargento, Teniente, Civil", max_length=50
                    ),
                ),
                ("fecha_ingreso", models.DateField(auto_now_add=True)),
                ("activo", models.BooleanField(default=True)),
                (
                    "tecnologias",
                    models.ManyToManyField(
                        related_name="expertos", to="personal.tecnologia"
                    ),
                ),
            ],
        ),
    ]
